//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaEFV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Business
    {
        public Business()
        {
            this.Locations = new HashSet<Location>();
            this.Voucher_Master = new HashSet<Voucher_Master>();
            this.Membership_Master = new HashSet<Membership_Master>();
        }
    
        public int Business_ID { get; set; }
        public string Business_Name { get; set; }
    
        public virtual Business_Details Business_Details { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<Voucher_Master> Voucher_Master { get; set; }
        public virtual ICollection<Membership_Master> Membership_Master { get; set; }
    }
}
