//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaEFV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Orders = new HashSet<Order>();
            this.Customer_Membership_Details = new HashSet<Customer_Membership_Details>();
        }
    
        public int Customer_ID { get; set; }
        public string Customer_Fname { get; set; }
        public string Customer_Lname { get; set; }
        public string Customer_Gender { get; set; }
        public string Customer_MobileNo { get; set; }
        public Nullable<System.DateTime> Customer_DOB { get; set; }
        public string Customer_EmailID { get; set; }
        public string Customer_AltMobileNo { get; set; }
        public int Customer_Created_Loc_ID { get; set; }
        public string Customer_CreatedBy { get; set; }
        public string Customer_Is_Active { get; set; }
        public System.DateTime Customer_Created_Dt { get; set; }
        public System.DateTime Customer_Updated_Dt { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Customer_Membership_Details> Customer_Membership_Details { get; set; }
    }
}
