//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaEFV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location_Tax
    {
        public Location_Tax()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Location_Tax_ID { get; set; }
        public int Location_ID { get; set; }
        public int Tax_ID { get; set; }
        public Nullable<decimal> Tax_Value { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Tax_Master Tax_Master { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
