//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaEFV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.Customers = new HashSet<Customer>();
            this.Location_Tax = new HashSet<Location_Tax>();
            this.Orders = new HashSet<Order>();
            this.Xref_Location_Service = new HashSet<Xref_Location_Service>();
            this.Xref_Location_Therapist = new HashSet<Xref_Location_Therapist>();
        }
    
        public int Loc_ID { get; set; }
        public int Business_ID { get; set; }
        public string Loc_Code { get; set; }
        public string Loc_Region { get; set; }
        public string Loc_Name { get; set; }
        public string Loc_Hotel_Name { get; set; }
        public string Loc_Spa_Name { get; set; }
        public string Loc_Address { get; set; }
        public string Loc_City { get; set; }
        public string Loc_State { get; set; }
        public string Loc_Country { get; set; }
        public string Loc_ContactNo { get; set; }
        public string Loc_Comment { get; set; }
        public string Loc_Is_Active { get; set; }
        public System.DateTime Loc_Created_Dt { get; set; }
        public System.DateTime Loc_Updated_Dt { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual LookUp_LocationRegion LookUp_LocationRegion { get; set; }
        public virtual ICollection<Location_Tax> Location_Tax { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Xref_Location_Service> Xref_Location_Service { get; set; }
        public virtual ICollection<Xref_Location_Therapist> Xref_Location_Therapist { get; set; }
    }
}
