//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaEFV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookUp_Country
    {
        public LookUp_Country()
        {
            this.LookUp_State = new HashSet<LookUp_State>();
            this.Tax_Master = new HashSet<Tax_Master>();
        }
    
        public int Country_ID { get; set; }
        public string Country_Name { get; set; }
    
        public virtual ICollection<LookUp_State> LookUp_State { get; set; }
        public virtual ICollection<Tax_Master> Tax_Master { get; set; }
    }
}
