//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaEFV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LookUp_Payment_Mode
    {
        public LookUp_Payment_Mode()
        {
            this.Order_Payment_Mode = new HashSet<Order_Payment_Mode>();
        }
    
        public int Payment_Mode_ID { get; set; }
        public string Payment_Mode_Code { get; set; }
        public string Payment_Mode_Description { get; set; }
    
        public virtual ICollection<Order_Payment_Mode> Order_Payment_Mode { get; set; }
    }
}
