//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaEFV3.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.ComponentModel.DataAnnotations;
  
    public partial class LookUp_Country
    {
        public LookUp_Country()
        {
            this.LookUp_State = new HashSet<LookUp_State>();
            this.Tax_Master = new HashSet<Tax_Master>();
        }

        [Display(Name = "Country ID")]
        public int Country_ID { get; set; }

        [Display(Name = "Country")]
        public string Country_Name { get; set; }

        [JsonIgnore]
        [IgnoreDataMember]
        public virtual ICollection<LookUp_State> LookUp_State { get; set; }

        [JsonIgnore]
        [IgnoreDataMember]
        public virtual ICollection<Tax_Master> Tax_Master { get; set; }
    }
}
