//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaEFV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Payment_Mode
    {
        public int Order_ID { get; set; }
        public int Payment_Mode_ID { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual LookUp_Payment_Mode LookUp_Payment_Mode { get; set; }
        public virtual Order Order { get; set; }
    }
}
