//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaEFV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Stock_Added = new HashSet<Stock_Added>();
            this.Treatment_Inventory_Usage = new HashSet<Treatment_Inventory_Usage>();
        }
    
        public int Product_ID { get; set; }
        public string Product_Name { get; set; }
        public Nullable<int> Product_Weight { get; set; }
        public string Product_Weight_UOM { get; set; }
        public decimal Product_MRP { get; set; }
        public Nullable<int> Product_Balance_Qty { get; set; }
        public Nullable<int> Product_Min_Stock_Lvl { get; set; }
        public string Product_Vendor { get; set; }
        public Nullable<System.DateTime> Product_MFG_Dt { get; set; }
        public Nullable<System.DateTime> Product_Expiry_Dt { get; set; }
        public string Product_Barcode { get; set; }
        public string Product_Description { get; set; }
        public System.DateTime Product_Created_Dt { get; set; }
        public System.DateTime Product_Updated_Dt { get; set; }
        public string Product_Created_By { get; set; }
    
        public virtual ICollection<Stock_Added> Stock_Added { get; set; }
        public virtual ICollection<Treatment_Inventory_Usage> Treatment_Inventory_Usage { get; set; }
    }
}
