//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaEFV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock_Added
    {
        public int Product_ID { get; set; }
        public Nullable<int> Qty_Added { get; set; }
        public System.DateTime Added_Dt { get; set; }
        public string Added_By { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
