//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaEFV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax_Master
    {
        public Tax_Master()
        {
            this.Location_Tax = new HashSet<Location_Tax>();
        }
    
        public int Tax_ID { get; set; }
        public int Country_ID { get; set; }
        public string Tax_Short_Name { get; set; }
        public string Tax_Description { get; set; }
    
        public virtual ICollection<Location_Tax> Location_Tax { get; set; }
        public virtual LookUp_Country LookUp_Country { get; set; }
    }
}
