//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaEFV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Therapist
    {
        public Therapist()
        {
            this.Xref_Location_Therapist = new HashSet<Xref_Location_Therapist>();
        }
    
        public int Therapist_ID { get; set; }
        public string Therapist_FName { get; set; }
        public string Therapist_LName { get; set; }
        public string Therapist_Gender { get; set; }
        public string Therapist_ContactNo { get; set; }
        public string Therapist_Is_Active { get; set; }
        public System.DateTime Therapist_Created_Dt { get; set; }
        public System.DateTime Therapist_Updated_Dt { get; set; }
    
        public virtual ICollection<Xref_Location_Therapist> Xref_Location_Therapist { get; set; }
    }
}
