//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaEFV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment
    {
        public Treatment()
        {
            this.Treatment_Inventory_Usage = new HashSet<Treatment_Inventory_Usage>();
            this.Xref_Service_Treatment = new HashSet<Xref_Service_Treatment>();
        }
    
        public int Treatment_ID { get; set; }
        public string Treatment_Name { get; set; }
        public string Treatment_Description { get; set; }
        public System.DateTime Treatment_Created_Dt { get; set; }
        public System.DateTime Treatment_Updated_Dt { get; set; }
        public string Treatment_Created_By { get; set; }
    
        public virtual ICollection<Treatment_Inventory_Usage> Treatment_Inventory_Usage { get; set; }
        public virtual ICollection<Xref_Service_Treatment> Xref_Service_Treatment { get; set; }
    }
}
