//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaEFV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment_Inventory_Usage
    {
        public int Treatment_ID { get; set; }
        public int Product_ID { get; set; }
        public Nullable<decimal> Qty_Used { get; set; }
        public int Treatment_Inventory_Usage_ID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Treatment Treatment { get; set; }
    }
}
