//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaEFV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Location_Access
    {
        public int User_Loc_Access_ID { get; set; }
        public string User_ID { get; set; }
        public int Loc_ID { get; set; }
        public string Permissions { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual User User { get; set; }
    }
}
