//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaEFV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserLogs = new HashSet<UserLog>();
            this.User_Location_Access = new HashSet<User_Location_Access>();
        }
    
        public string User_ID { get; set; }
        public string Pwd { get; set; }
        public string Role { get; set; }
        public string User_Fname { get; set; }
        public string User_Lname { get; set; }
        public string User_Is_Active { get; set; }
        public System.DateTime User_Created_Dt { get; set; }
        public System.DateTime User_Updated_Dt { get; set; }
    
        public virtual UserRole UserRole { get; set; }
        public virtual ICollection<UserLog> UserLogs { get; set; }
        public virtual ICollection<User_Location_Access> User_Location_Access { get; set; }
    }
}
