//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaEFV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Xref_Service_Treatment
    {
        public int Service_Treatment_Xref_ID { get; set; }
        public int Service_ID { get; set; }
        public int Treatment_ID { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual Treatment Treatment { get; set; }
    }
}
